### ISSUE TITLE
Assignment - Define the Project Architecture [due week 4]

### ISSUE THREAD

**Issue by PALEJADISA** [SylviaHJY/Wardrobe-Wizard#1]
Before we move into Sprint one, we need to ensure the following:

that there is clarity on the vision and scope for your project - this we covered in week #3, 
that there is clarity on the conceptual solution architecture -  this we covered in week #4, and 
that you have been able to refine and prioritize the work that you plan to complete in your first phase of development. 
This assignment will cover the last item, sprint planning, in order to ensure that your team will be ready to move into an agile development cycle beginning with Sprint One.  Here are your deliverables

Create a requirements page in your project's GitHub wiki where you can put any documentation of the requirements for your project.  These Wiki pages are not intended for project management, so don't put any detailed tasks or users stories here, as we will use GitHub issues for those.    The Wiki is rather a place where one could go to see an overall view of the project.
Create the project's initial backlog of work items or tasks.   Create these as GitHub "[IssuesLinks to an external site.](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues)".  User stories are a standard pattern for representing requirements in a backlog.
Create five "[MilestonesLinks to an external site.](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones)" in your project, one for each of our five planned sprints.  As part of your sprint planning, you should decide which issues to work on in the first sprint, and then move these backlog items into the the Sprint 1 milestone to define what you will work on in Sprint one.
Assign work items to each member of the team.
You should also create a "Project" in GitHub so that you can better track and manage the progress of each sprint.   You can create "boards" (e.g. "Kanban") and move items between boards to track your work.    You can use any type of board but it should have at least a column for to hold items that are not yet done.   Use the newer style of GitHub "Projects", not the Classic - instead use this style:  [GitHub ProjectLinks to an external site.](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects) which has more features.   
Submit this assignment with a statement confirming these are done so that I know I can review.

**Comment by SylviaHJY** [comment]
Not a issue
